--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: petclinicapproject
 labels: 
  app: petclinic2
spec:
 selector:
  matchLabels:
   app: petclinic2
 strategy: 
  type: Recreate
 template: 
  metadata: 
   labels: 
    app: petclinic2
    tier: petclinic
  spec:
   containers:
   - name: petclinic2
     image: "gcr.io/test-baobab/tomcat:latest"
     imagePullPolicy: Always
     ports:
     - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
 labels: 
  app: petclinic
 name: petclinicservice
spec:
 ports: 
 - port: 8080
   targetPort: 8080
 selector: 
  app: petclinic
  tier: petclinic
spec:
 type: LoadBalancer
