--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hello
 labels: 
  app: petclinic
spec:
 strategy: 
  type: Recreate
 template: 
  metadata: 
    labels: 
      app: petclinic
      tier: petclinic
spec: 
 containers: 
 - name: petclinic
   image: "gcr.io/test-baobab/tomcat:latest"
   imagePullPolicy: Always
   ports: 
   - containerPort: 8080

--- 
apiVersion: v1
kind: Service
labels: 
  app: petclinic
metadata:
 name: hello
spec:
 ports: 
  - port: 8080
    targetPort: 8080
 selector: 
  app: petclinic
  tier: petclinic
spec:
type: LoadBalancer
