--- 
apiVersion: apps/v1
kind: Deployment
labels: 
  app: petclinic
metadata: ~
name: hello
spec: ~
strategy: 
  type: Recreate
template: 
  metadata: 
    labels: 
      app: petclinic
      tier: petclinic
  spec: 
    containers: 
      - 
        image: "gcr.io/test-baobab:tomcat:latest"
        imagePullPolicy: Always
        name: petclinic
        ports: 
          - 
            containerPort: 8080
            name: hello

--- 
apiVersion: v1
kind: Service
labels: 
  app: petclinic
metadata: ~
name: hello
ports: 
  - 
    port: 8080
    targetPort: 8080
selector: 
  app: petclinic
  tier: petclinic
spec: ~
type: LoadBalancer
